name: roms_downloader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests>=2.25.0
  - pip
  - pip:
    - requests
    - pyinstaller
    - watchdog
    - nsz
    - kivy
    - kivymd